### ISSUE TITLE
write new scraper

### ISSUE THREAD

**Issue by willkg** [pyvideo/steve#24]
@codersquid started some scraping code to replace vidscraper.

https://gist.github.com/codersquid/8c1aa67f29c97ad0572f

We should base the new scraper on that. If we make it pluggable, that'll make it easier to use/extend later, too.

**Comment by willkg** [comment]
Further, this comment is relevant as well:

https://github.com/pyvideo/steve/issues/22#issuecomment-60100721

**Comment by willkg** [comment]
A couple of weeks ago, I discovered youtube-dl had a `-j` parameter that spit out JSON. Game-changer.

I talked to @codersquid about that and she said it sounded interesting to try out.

I got some time this evening and threw together the vestiges of a scraping system that has a YoutubeScraper that uses youtube-dl. That's in https://github.com/pyvideo/steve/commit/6561a74c9d22d3547f6740676a86dbf83ef2be2f

The actual scraping works super as far as I've tested. The infrastructure and ability to extend the scraping system sucks. However, this is functional enough that it should make it easier to work through the pyvideo queue. "Good enough for now."

**Comment by codersquid** [comment]
I tried this out for PyCon Italia. First thing I've noticed is that some of the videos do not have an entry for source url.

**Comment by codersquid** [comment]
ixnay empty source-url entries, that was due to something else. my apologies.

First thing I notice is that it's slow, but that's not a big deal.

Field mappings:
* I prefer to put youtube descriptions in to the 'description' field, not the 'summary' field.
* I prefer to ignore youtube tags. they are always useless

I can change those, or leave as is if you have a reason for wanting them mapped that way.

**Comment by codersquid** [comment]
It saves entries in 'live' mode.

**Comment by willkg** [comment]
"summary" is really important since it shows up in the video lists and in some cases it's really the only thing that tells you what the video is about. Generally, I've seen people putting short descriptions on YouTube which work well as summaries in pyvideo. I think the only huge exception to that is the data conferences. It should be pretty easy to write a script to move them post-fetch.

I'm game for switching this, but it seems like it's a better default in regards to how much work is required for post processing.

For YouTube tags, I suggest writing a post-fetch script that wipes out useless ones. Occasionally we've seen useful ones and if the scraper doesn't capture them, then there's no way to do it by hand. It's easier to remove things post-fetch than add things that didn't exist.

Do you still want to change this? If so, writing up a PR is probably the easiest thing to do. Otherwise I'll get to it when I get to it.

**Comment by codersquid** [comment]
On Mon, Jun 15, 2015 at 9:12 AM, Will Kahn-Greene <notifications@github.com>
wrote:

> Do you still want to change this? If so, writing up a PR is probably the
> easiest thing to do. Otherwise I'll get to it when I get to it.


Nope.

summary: I think I was biased to put things in description vs. summary
because I've seen either nothing or long descriptions in youtube videos
(maybe it's the scipy and pydata folks). (I do like when there are short
summaries. sometimes I go through things by hand to add them).

tags: okay, good point. and I usually end up writing something to strip
them out, or call perl -pi -e.

-- 
shekay@pobox.com

**Comment by willkg** [comment]
> It saves entries in 'live' mode.

I fixed that with issue #27.

I think that was the only thing we needed to do here, so I'm going to close this out.
